spring:
  application:
    name: websocketV1

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, threaddump
  endpoint:
    threaddump:
      enabled: true
    health:
      show-details: always
  
logging:
  level:
    com.study.websocketV1: DEBUG
  pattern:
    onsole: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{20} - %msg%n"